import Link from "next/link";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Home_Route, Login_Route} from "@/constants/routes";
import hamroPasal from "@/assets/hamroPasal.png";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Notification from "@/components/Notification";


export const metadata = {
  title: "First nextJs app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <body>
        <Notification/>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
