import Link from "next/link";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Home_Page, Login_Page} from "@/constants/routes";


export const metadata = {
  title: "First nextJs app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header className="bg-primary-50">
          <div className="md:container flex mx-auto justify-between items-center h-16 relative">

            {/* redirect to Home_Page */}
            <Link href={`${Home_Page}`}>LOGO</Link>

            <div className='flex justify-between p-4 gap-4'>
              {/* navigation */}
              <Navbar/>

              {/* login page  */}
              <Link href={`${Login_Page}`}className='p-1 rounded text-white text-sm bg-primary-500'>LOGIN</Link>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
